"""Centralized configuration constants for the ATS CV Optimizer project."""

from __future__ import annotations

# Consumers should import using:
# from config.constants import (
#     ALLOWED_EXTENSIONS,
#     MAX_FILE_SIZE_MB,
#     APPROVED_ACTION_VERBS,
#     BANNED_TERMS,
#     STOPWORDS,
#     CONFIGURATION_RULES,
# )

ALLOWED_EXTENSIONS = ["pdf", "docx", "txt"]
MAX_FILE_SIZE_MB = 5

APPROVED_ACTION_VERBS = [
    "achieved",
    "activated",
    "adapted",
    "addressed",
    "administered",
    "advanced",
    "advised",
    "aligned",
    "analyzed",
    "architected",
    "assembled",
    "assessed",
    "assisted",
    "automated",
    "built",
    "calibrated",
    "clarified",
    "coached",
    "collaborated",
    "communicated",
    "compiled",
    "completed",
    "conducted",
    "consolidated",
    "constructed",
    "consulted",
    "controlled",
    "coordinated",
    "crafted",
    "created",
    "customized",
    "debugged",
    "delivered",
    "designed",
    "developed",
    "devised",
    "diagnosed",
    "directed",
    "discovered",
    "documented",
    "drove",
    "educated",
    "eliminated",
    "enabled",
    "engineered",
    "enhanced",
    "ensured",
    "established",
    "evaluated",
    "executed",
    "expanded",
    "facilitated",
    "forecasted",
    "formalized",
    "formulated",
    "generated",
    "guided",
    "implemented",
    "improved",
    "increased",
    "influenced",
    "initiated",
    "innovated",
    "integrated",
    "launched",
    "led",
    "maintained",
    "managed",
    "mentored",
    "migrated",
    "modernized",
    "monitored",
    "optimized",
    "orchestrated",
    "organized",
    "oversaw",
    "owned",
    "partnered",
    "pioneered",
    "planned",
    "prioritized",
    "produced",
    "programmed",
    "re-architected",
    "realigned",
    "reduced",
    "refactored",
    "resolved",
    "revamped",
    "reviewed",
    "saved",
    "shipped",
    "simplified",
    "solved",
    "standardized",
    "streamlined",
    "strengthened",
    "supervised",
    "supported",
    "spearheaded",
    "trained",
    "transformed",
    "upgraded",
    "validated",
]

BANNED_TERMS = [
    "10x engineer",
    "action-oriented rockstar",
    "best-in-class",
    "blue-sky thinking",
    "boil the ocean",
    "circle back",
    "disruptor",
    "game changer",
    "go-getter",
    "guru",
    "high-octane",
    "ideation ninja",
    "innovative wizard",
    "leverage (as noun)",
    "low-hanging fruit",
    "mission critical rockstar",
    "move the needle",
    "next-gen unicorn",
    "outside-the-box thinker",
    "paradigm shift",
    "rockstar",
    "synergy",
    "thought leader",
    "value-add guru",
    "visionary ninja",
    "wheelhouse",
    "world-class",
]

STOPWORDS = {
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can't",
    "cannot",
    "could",
    "couldn't",
    "did",
    "didn't",
    "do",
    "does",
    "doesn't",
    "doing",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn't",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "he'd",
    "he'll",
    "he's",
    "her",
    "here",
    "here's",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "how's",
    "i",
    "i'd",
    "i'll",
    "i'm",
    "i've",
    "if",
    "in",
    "into",
    "is",
    "isn't",
    "it",
    "it's",
    "its",
    "itself",
    "let's",
    "me",
    "more",
    "most",
    "mustn't",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "shan't",
    "she",
    "she'd",
    "she'll",
    "she's",
    "should",
    "shouldn't",
    "so",
    "some",
    "such",
    "than",
    "that",
    "that's",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "there's",
    "these",
    "they",
    "they'd",
    "they'll",
    "they're",
    "they've",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "wasn't",
    "we",
    "we'd",
    "we'll",
    "we're",
    "we've",
    "were",
    "weren't",
    "what",
    "what's",
    "when",
    "when's",
    "where",
    "where's",
    "which",
    "while",
    "who",
    "who's",
    "whom",
    "why",
    "why's",
    "with",
    "won't",
    "would",
    "wouldn't",
    "you",
    "you'd",
    "you'll",
    "you're",
    "you've",
    "your",
    "yours",
    "yourself",
    "yourselves",
}

CONFIGURATION_RULES = {
    "enforce_unique_words": True,
    "enforce_stopword_ban": False,
    "enforce_banned_terms": True,
    "enforce_min_word_count": True,
}

__all__ = [
    "ALLOWED_EXTENSIONS",
    "MAX_FILE_SIZE_MB",
    "APPROVED_ACTION_VERBS",
    "BANNED_TERMS",
    "STOPWORDS",
    "CONFIGURATION_RULES",
]
